version: "3.8"

services:

    nginx_resource_server:
        restart: always
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - 80:80
        depends_on:
            - flask_resource
        command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/main/static:/etc/nginx/static
        env_file:
            - .env

    flask_resource:
        build: .
        env_file:
            - .env
        volumes:
            - .:/app:rw
        restart: always
        container_name: flask
        depends_on:
            - db_flask_resource
        command: gunicorn run:app -w 4 -b 0.0.0.0:5000 --worker-tmp-dir /dev/shm --timeout 6000 --preload
        entrypoint: /app/entrypoint.sh
        expose:
            - 5000

    db_flask_resource:
        restart: always
        image: postgres:14.4-alpine
        container_name: postgres
        env_file:
            - .env
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
